import "./globals.css";
import { HeaderStart } from "./components/header.jsx";
import { Footer } from "./components/footer.jsx";
import { TopNav } from "./components/top-nav/top-nav.jsx";

export const metadata = {
  title: "YrgoLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <TopNav/>
        <HeaderStart />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
