import "./globals.css";
import { Footer } from "./components/footer.jsx";
import { Main } from "./components/Main";
import { Header } from "./components/common/Header";

export const metadata = {
  title: "YrgoLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="sv">
      <body>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
